### ISSUE TITLE
No support for metaprogramming

### ISSUE THREAD

**Issue by HugoFarias** [adamlazz/language-maude#3]
Maude has metaprogramming but the package cannot support this syntax. For example, if you write a metamodule inside an equation the rest of module won't be highlighted properly.
In my repo named learn there is a source in Maude with metaprogramming that is an example of this issue.

**Comment by adamlazz** [comment]
Hi Hugo, thanks for using the package.
I don't have the experience with Maude or dealing with grammars of this size to build support for metaprogramming. Spare time is also an issue.

The original tmbundle was written by @mkhl, and I simply converted the tmbundle to an Atom package.

If you make any progress, please let me know and I will happily take a look.

**Comment by mkhl** [comment]
Hi Hugo, could you be more specific regarding which part of which module you find doesn't highlight correctly?

On first glance (in TextMate, I'm not an Atom user), I didn't see any obvious errors, maybe there is a problem with the conversion or some limitation of Atom itself that causes this?

**Comment by HugoFarias** [comment]
In this case I have an equation, transformLearnCourse of module TRANSFORM-LEARN, whose output is a meta-module. After this the highlight is different from before.
In the images below it can be seen.

![img_1](https://cloud.githubusercontent.com/assets/8578628/11499423/3899b082-980d-11e5-929c-896f4b4895e1.png)
![img_2](https://cloud.githubusercontent.com/assets/8578628/11499424/389bba26-980d-11e5-9341-3c3ce399d0e7.png)

Thanks for the attention.

**Comment by mkhl** [comment]
Got it. We can include the `#module` repository in the patterns of `meta.equation.eq.rhs.maude` and `meta.equation.ceq.rhs.maude`. Otherwise the grammar thinks that the `.` inside the inner module ends the `eq`, leaving the `endm` of the inner mod to end the toplevel module.

Are there any other places where modules or theories can be nested?

**Comment by HugoFarias** [comment]
Maybe can be possible but in my use I only discovered this case.

**Comment by mkhl** [comment]
Alright.

@adamlazz I’ve pushed mkhl/maude.tmbundle@2996947 which seems to fix this issue for me.

**Comment by adamlazz** [comment]
Great. Thanks @mkhl. I will update the package tonight.

**Comment by adamlazz** [comment]
Just published 0.3.0 @HugoFarias. Let me know if it works.

I re-initialized the package to incorporate the changes.

**Comment by HugoFarias** [comment]
Yes, it worked!
Thank you, @adamlazz!
